services:
  postgres:
    image: postgres:16-alpine
    container_name: tasker_postgres_infra
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-tasker}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-tasker}
      POSTGRES_DB: ${POSTGRES_DB:-tasker}
    volumes:
      - pgdata_infra:/var/lib/postgresql/data
    networks:
      - tasker_net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-tasker}"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  # Optional tooling - comment out if not needed
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: tasker_pgadmin_infra
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL:-admin@example.com}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: "False"
    networks:
      - tasker_net
    depends_on:
      - postgres
    restart: unless-stopped

networks:
  tasker_net:
    driver: bridge
    name: tasker_net

volumes:
  pgdata_infra:
    name: tasker_pgdata_infra